// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_dev.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxYwQkwnB8iURFmLZNyKBa_OGR3WKHKkg',
    appId: '1:888584026866:web:e66d62f7256a1007696e6b',
    messagingSenderId: '888584026866',
    projectId: 'smartstock-dev-63be8',
    authDomain: 'smartstock-dev-63be8.firebaseapp.com',
    storageBucket: 'smartstock-dev-63be8.firebasestorage.app',
    measurementId: 'G-YZC1EK42T0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD36r0bzQvoZKLpZsayfU8QIL3y0n7Y9NA',
    appId: '1:888584026866:android:aa14210512237d07696e6b',
    messagingSenderId: '888584026866',
    projectId: 'smartstock-dev-63be8',
    storageBucket: 'smartstock-dev-63be8.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDxYwQkwnB8iURFmLZNyKBa_OGR3WKHKkg',
    appId: '1:888584026866:web:b7bbb20a7fdac121696e6b',
    messagingSenderId: '888584026866',
    projectId: 'smartstock-dev-63be8',
    authDomain: 'smartstock-dev-63be8.firebaseapp.com',
    storageBucket: 'smartstock-dev-63be8.firebasestorage.app',
    measurementId: 'G-B49HKK400G',
  );
}
