// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9v5g7n2fZiQ7ucyEFmuYejIYskd5hLYg',
    appId: '1:986101154255:web:8b5beead82f494085a12ba',
    messagingSenderId: '986101154255',
    projectId: 'smartstock-f47d5',
    authDomain: 'smartstock-f47d5.firebaseapp.com',
    storageBucket: 'smartstock-f47d5.firebasestorage.app',
    measurementId: 'G-MB79HDPP87',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRcK8cZjJbTQsGy2kW6QG7zPknY2G-zlc',
    appId: '1:986101154255:android:024d614508a8c7d45a12ba',
    messagingSenderId: '986101154255',
    projectId: 'smartstock-f47d5',
    storageBucket: 'smartstock-f47d5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLJgizAljjzCSoK2dvCCJAEpKAPsVn3oc',
    appId: '1:986101154255:ios:3dedcf24e8fbf9fd5a12ba',
    messagingSenderId: '986101154255',
    projectId: 'smartstock-f47d5',
    storageBucket: 'smartstock-f47d5.firebasestorage.app',
    iosBundleId: 'com.smartstock.smartstock',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB9v5g7n2fZiQ7ucyEFmuYejIYskd5hLYg',
    appId: '1:986101154255:web:81017385c77ccf0d5a12ba',
    messagingSenderId: '986101154255',
    projectId: 'smartstock-f47d5',
    authDomain: 'smartstock-f47d5.firebaseapp.com',
    storageBucket: 'smartstock-f47d5.firebasestorage.app',
    measurementId: 'G-MT779KPSDG',
  );
}
